// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAosm3pOInH5K-E7gbKaidfn9kLsYnQHkc',
    appId: '1:1082667359582:web:8e6aac021b8e0a60eb03cf',
    messagingSenderId: '1082667359582',
    projectId: 'flutter-auth-write-read',
    authDomain: 'flutter-auth-write-read.firebaseapp.com',
    storageBucket: 'flutter-auth-write-read.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1-lk88wlxO83ZPMONDhODD2PRgMhswqw',
    appId: '1:1082667359582:android:3a6202def3be4f1eeb03cf',
    messagingSenderId: '1082667359582',
    projectId: 'flutter-auth-write-read',
    storageBucket: 'flutter-auth-write-read.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8LkrAWjN0_3KQvMazaNBk3XkQP2icSdA',
    appId: '1:1082667359582:ios:3c1477034003330beb03cf',
    messagingSenderId: '1082667359582',
    projectId: 'flutter-auth-write-read',
    storageBucket: 'flutter-auth-write-read.appspot.com',
    iosBundleId: 'com.example.firebaseWriteReadAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8LkrAWjN0_3KQvMazaNBk3XkQP2icSdA',
    appId: '1:1082667359582:ios:af327409dcc7ac5deb03cf',
    messagingSenderId: '1082667359582',
    projectId: 'flutter-auth-write-read',
    storageBucket: 'flutter-auth-write-read.appspot.com',
    iosBundleId: 'com.example.firebaseWriteReadAuth.RunnerTests',
  );
}
